config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks do
    patch "move", on: :member
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true

  enum status: {
    not_yet_started: "not_yet_started",
    in_progress: "in_progress",
    completed: "completed",
  }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy move ]

  def move
    if @task.not_yet_started?
      @task.in_progress!
    elsif @task.in_progress?
      @task.completed!
    else
      @task.in_progress!
    end
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task updated" }
      format.js
    end
  end

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render "shared/cdn_assets" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mb-5">
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_cdn_assets.html.erb
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light mb-3">
  <div class="container">
    <a class="navbar-brand" href="#">Tasks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<li id="<%= dom_id task, :form %>" class="list-group-item">
  <%= form_with(model: task, local:false) do |form| %>
    <div class="mb-2">
      <%= form.label :content, class: "visually-hidden" %>
      <%= form.text_field :content, class: "form-control" %>
    </div>
    <div>
      <div class="d-grid">
        <%= form.submit class: "btn btn-outline-primary " %>
      </div>
    </div>
  <% end %>
</li>

app/views/tasks/_task.html.erb
<li id="<%= dom_id(task) %>" class="list-group-item">
  <div>
    <%= task.content %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="d-grid gap-2">
        <%= link_to move_task_path(task), class: "btn btn-link", method: :patch, remote: true do %>
          <% if task.not_yet_started? %>
            <i class="fa-sharp fa-solid fa-play"></i>
          <% elsif task.in_progress? %>
            <i class="fa-regular fa-circle-check"></i>
          <% else %>
            <i class="fa-sharp fa-solid fa-backward"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="d-grid gap-2">
        <%= link_to edit_task_path(task), remote:true, class: "btn btn-link" do %>
          <i class="fa-sharp fa-solid fa-pen-to-square"></i>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="d-grid gap-2">
        <%= link_to task, method: :delete, remote:true, class: "btn btn-link" do %>
          <i class="fa-sharp fa-solid fa-trash-can"></i>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/tasks/create.js.erb
var new_task = $("<%= j(render @task) %>");

new_task.hide();

$("#form_task").after(new_task);

new_task.slideDown();

$("#form_task #task_content").val("");

app/views/tasks/destroy.js.erb
$("#<%= dom_id @task %>").fadeOut();
$("#<%= dom_id @task %>").slideUp(function() {
this.remove();
});

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$("#<%= dom_id @task %>").replaceWith("<%= j(render "tasks/form", task: @task)%>");

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        Not yet started
      </div>

      <ul id="not_yet_started_list" class="list-group list-group-flush">
        <%= render 'tasks/form', task: current_user.tasks.build %>
        <%= render current_user.tasks.not_yet_started.order(created_at: :asc) %>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        In progress
      </div>
      <ul id="in_progress_list" class="list-group list-group-flush">
        <%= render current_user.tasks.in_progress.order(updated_at: :desc) %>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        Completed
      </div>
      <ul id="completed_list" class="list-group list-group-flush">
        <%= render current_user.tasks.completed.order(updated_at: :desc) %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/move.js.erb
$("#<%= dom_id @task %>").remove();

var updated_task = $("<%= j(render @task) %>");

$("#<%= @task.status %>_list").prepend(updated_task);

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$("#<%= dom_id @task, :form %>").replaceWith("<%= j(render @task)%>");